theme: jekyll-theme-cayman
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: ecem202a_project
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
