
YOLOv4_TINY_MODEL_DIR = './yolov4/'

RED_LIGHT_DURATION_RANGE = (2, 3)
RED_LIGHT_POST_DETECTION_DURATION = (2, 2)
GREEN_LIGHT_DURATION_RANGE = (1.5, 2.5)

N_TOTAL_GREEN_LIGHT_STATES = 10

LASER_FIRE_DELAY = 0.5
