
YOLOv4_TINY_MODEL_DIR = './yolov4/'

RED_LIGHT_DURATION_RANGE = (4, 6)
RED_LIGHT_POST_DETECTION_DURATION = (3, 3)
GREEN_LIGHT_DURATION_RANGE = (4, 6)

N_TOTAL_GREEN_LIGHT_STATES = 5

LASER_FIRE_DELAY = 0.5
